version: 2
jobs:
    build:
      docker:
          - image: circleci/python:3.6.1

      working_directory: ~/repo

      steps:
          - checkout

          - run:
              name: install dependencies
              command: |
                  pip install django flake8

          - run:
              name: run tests
              command: |
                  python django-basic/manage.py migrate;
                  python django-basic/manage.py test;
                  flake8 --exclude polls/migrations/,manage.py  .;
