version: 2
jobs:
    build:
      working_directory: ~/GCS01/django-basic
      docker:
          - image: circleci/python:3.6.1
            environment:
                   PYTHONPATH: $PWD

      steps:
          - checkout

          - run:
              name: install dependencies
              command: |
                  python3 -m venv venv
                  . venv/bin/activate
                  pip install django flake8

          - run:
              name: run tests
              command: |
                  . venv/bin/activate
                  python django-basic/manage.py migrate
                  python django-basic/manage.py test
                  flake8 --exclude django-basic/polls/migrations/,manage.py  .

