version: 2
jobs:
    build:
      working_directory: ~/GCS01/django-basic
      docker:
          - image: circleci/python:3.6.1

      steps:
          - checkout

          - run:
              name: install dependencies
              command: |
                  python3 -m venv venv
                  . venv/bin/activate
                  pip install django flake8

          - run:
              name: run tests
              command: |
                  . venv/bin/activate
                  python manage.py migrate
                  export PYTHONPATH=`pwd`
                  python manage.py test
                  flake8 --exclude polls/migrations/,manage.py  .

